name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  gradle-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build --scan

  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: ./red-chariot-command
            image-suffix: command
          - context: ./red-chariot-query/red-chariot-messaging
            image-suffix: query-messaging
          - context: ./red-chariot-query/red-chariot-user
            image-suffix: query-user
          - context: ./red-chariot-it
            image-suffix: it
          - context: ./red-chariot-ui
            image-suffix: ui
    permissions:
      contents: read
      packages: write
    needs:
      - gradle-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for red-chariot-command Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.image-suffix }}
          tags: |
            type=ref,event=branch

      - name: Build and push Docker image for red-chariot-command
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}